name: .NET Core

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]




jobs:
  build:

    defaults:
      run:
        working-directory: src/PietSharp/

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
      # Generate the website
    - name: Publish
      run: dotnet publish PietSharp.Blazor/PietSharp.Blazor.csproj --configuration Release

    # Publish the website
    - name: GitHub Pages action
      if: ${{ github.ref == 'refs/heads/master' }} # Publish only when the push is on master
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.PUBLISH_TOKEN }}
        publish_branch: gh-pages
        publish_dir: bin/Release/net5.0/publish/wwwroot
        allow_empty_commit: false
        keep_files: false
        force_orphan: true
